spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://qrxplbvgoxovol:0ca027c158af035dc766da09371932413dd26e8908a5ad9a326a6c3f56c22b2a@ec2-75-101-131-79.compute-1.amazonaws.com:5432/d2ded26j0d5bcj/d2ded26j0d5bcj?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: qrxplbvgoxovol
    password: 0ca027c158af035dc766da09371932413dd26e8908a5ad9a326a6c3f56c22b2a
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false