spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://pekeciogdimvtg:c443bcf33a3a030dd4afe3fa075243dbf57de811a46b5c42c72fece040325bc5@ec2-184-73-153-64.compute-1.amazonaws.com:5432/d3gmam2dfni0ot/d3gmam2dfni0ot?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: pekeciogdimvtg
    password: c443bcf33a3a030dd4afe3fa075243dbf57de811a46b5c42c72fece040325bc5
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false