spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://hfnftpedbdttvd:dd084e7f9751af376b14b8f1cb74c563bad43f602d16b48abfadd9b40c52d72c@ec2-54-221-201-212.compute-1.amazonaws.com:5432/d5l3rg3ja2cbuh/d5l3rg3ja2cbuh?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: hfnftpedbdttvd
    password: dd084e7f9751af376b14b8f1cb74c563bad43f602d16b48abfadd9b40c52d72c
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false